// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mowei.Stock.Models;

namespace Mowei.Stock.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201024032209_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mowei.Stock.Models.FundamentalDaily", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stock_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Dividend_yield")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Pe_ratio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Price_book_ratio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Date", "Stock_id");

                    b.ToTable("FundamentalDaily");
                });

            modelBuilder.Entity("Mowei.Stock.Models.TWStockPrice", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stock_id")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Min")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Spread")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Trading_money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Trading_turnover")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Trading_volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Date", "Stock_id");

                    b.ToTable("TWStockPrice_History");
                });
#pragma warning restore 612, 618
        }
    }
}
